### ISSUE TITLE
Block service serves data stored the same differently based on other factors

### ISSUE THREAD

**Issue by fantasticsquirrel** [Lamden/lamden_block_service#33]
**Lst003**
`collection_nfts[name] = {"description": description, "ipfs_image_url": ipfs_image_url, "metadata": metadata, "amount": amount}`

**Harvest** (https://www.tauhq.com/contracts/con_harvest_002)
`collection_nfts[name] = {"description": description, "ipfs_image_url": ipfs_image_url, "nft_metadata": f"See collection_nfts[{name},'nft_metadata']", "amount": amount}`

 Harvest has other data stored under `collection_nfts[name, 'nft_metadata']` which makes the block explorer return data for `collection_nfts[name]` under "__hash_self__" which is different to how the data would display otherwise. This leads to issues with services using the block service because the same exact data can be served in 2 different ways. 
![image](https://user-images.githubusercontent.com/95108850/191491405-dfdc34bf-15cd-42fc-8ce2-13a60908d3d5.png)

**Comment by crosschainer** [comment]
https://blockservice.nebulamden.finance/current/all/con_thatguyorigins/collection_nfts/Gabriel
vs
https://blockservice.nebulamden.finance/current/all/con_harvest_002/collection_nfts/Gen_2_1

**Comment by JeffWScott** [comment]
This is a work around because hash objects are not json objects and that's what we are attempting to serve.
